/**
 * Orbit & Ember Kitchen + Bar — Authoritative Normalized Menu Source of Truth
 * Version: 2.0.0 (Shared Layer)
 * Last Reviewed: 2026-07-24
 */

window.ORBIT_MENU_DATA = {
  version: "2.0.0",
  lastReviewed: "2026-07-24",
  services: [
    { id: "dinner", title: "Dinner Service", shortLabel: "Dinner", hours: "5:00 PM – 10:00 PM Daily" },
    { id: "brunch", title: "Weekend Brunch", shortLabel: "Brunch", hours: "Sat & Sun 10:00 AM – 2:30 PM" },
    { id: "drinks", title: "Craft Bar & Zero-Proof", shortLabel: "Bar", hours: "Open Daily 4:00 PM – Late" },
    { id: "dessert", title: "Dessert & After Dark", shortLabel: "Dessert", hours: "Nightly 5:00 PM – Late" }
  ],
  items: [
    // DINNER MAINS & GRILL
    {
      id: "menu-black-garlic-short-rib",
      slug: "black-garlic-short-rib",
      name: "Black Garlic Braised Short Rib",
      shortName: "Black Garlic Short Rib",
      description: "Slow-braised over cured oak for 14 hours with fermented black garlic jus, charred cipollini onions, and smoked parsnip puree.",
      serviceIds: ["dinner"],
      sectionId: "dinner-mains",
      category: "main",
      pricing: { type: "fixed", baseAmount: 34, currency: "USD", display: "$34" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["CF", "GF"],
      allergenMarkers: ["Soy"],
      flavorTags: ["Smoky", "Deep", "Savory", "Rich"],
      mealStyleTags: ["Main", "Focused Plate"],
      shareable: false,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "featured-steak",
      imagePath: "images/featured-steak.jpg",
      pairingIds: ["pair-short-rib-copper-moon", "pair-short-rib-lunar-bloom"]
    },
    {
      id: "menu-ember-roasted-chicken",
      slug: "ember-roasted-chicken",
      name: "Wood-Fired Ember Chicken",
      shortName: "Ember Chicken",
      description: "Half pasture-raised chicken roasted on cured oak hearth coals with Meyer lemon glaze, roasted garlic, and charred broccolini.",
      serviceIds: ["dinner"],
      sectionId: "dinner-mains",
      category: "main",
      pricing: { type: "fixed", baseAmount: 28, currency: "USD", display: "$28" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["GF"],
      allergenMarkers: [],
      flavorTags: ["Smoky", "Citrus", "Savory", "Fresh"],
      mealStyleTags: ["Main"],
      shareable: false,
      alcoholStatus: false,
      zeroProof: false,
      featured: false,
      imageId: "wood-fired-hearth",
      imagePath: "images/wood-fired-hearth.jpg",
      pairingIds: ["pair-chicken-first-light"]
    },
    {
      id: "menu-wood-fired-mushrooms",
      slug: "wood-fired-mushrooms",
      name: "Hearth-Roasted Wild Mushrooms",
      shortName: "Charred Mushrooms",
      description: "Foraged maitake and king oyster mushrooms roasted over live coals with thyme butter, crispy shallots, and aged sherry glaze.",
      serviceIds: ["dinner", "brunch"],
      sectionId: "dinner-mains",
      category: "main",
      pricing: { type: "fixed", baseAmount: 24, currency: "USD", display: "$24" },
      active: true,
      seasonal: true,
      seasonalLabel: "Autumn Harvest",
      dietaryMarkers: ["V", "GF", "VG-Option"],
      allergenMarkers: ["Dairy"],
      flavorTags: ["Smoky", "Earthy", "Rich", "Herbal"],
      mealStyleTags: ["Starter", "Shared"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "wood-fired-hearth",
      imagePath: "images/wood-fired-hearth.jpg",
      pairingIds: ["pair-mushrooms-copper-moon"]
    },
    {
      id: "menu-charred-carrots",
      slug: "charred-carrots",
      name: "Coal-Roasted Carrots & Whipped Feta",
      shortName: "Charred Carrots",
      description: "Heirloom carrots blistered in live coals over sheep's milk feta, hot honey drizzle, and toasted pistachio dukkah.",
      serviceIds: ["dinner", "brunch"],
      sectionId: "dinner-starters",
      category: "starter",
      pricing: { type: "fixed", baseAmount: 16, currency: "USD", display: "$16" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["V", "GF", "SP"],
      allergenMarkers: ["Dairy", "Tree Nuts", "Honey"],
      flavorTags: ["Smoky", "Sweet", "Spiced", "Fresh"],
      mealStyleTags: ["Starter", "Shared"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "wood-fired-hearth",
      imagePath: "images/wood-fired-hearth.jpg",
      pairingIds: ["pair-carrots-solar-flare"]
    },
    {
      id: "menu-smoked-pepper-flatbread",
      slug: "smoked-pepper-flatbread",
      name: "Hearth-Baked Smoked Pepper Flatbread",
      shortName: "Smoked Flatbread",
      description: "Hand-stretched sourdough charred in 800° hearth with wood-roasted sweet peppers, fresh stracciatella, and basil.",
      serviceIds: ["dinner", "brunch"],
      sectionId: "dinner-starters",
      category: "starter",
      pricing: { type: "fixed", baseAmount: 18, currency: "USD", display: "$18" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["V"],
      allergenMarkers: ["Gluten", "Dairy"],
      flavorTags: ["Smoky", "Fresh", "Savory", "Comforting"],
      mealStyleTags: ["Starter", "Shared"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "featured-flatbread",
      imagePath: "images/featured-flatbread.jpg",
      pairingIds: ["pair-flatbread-solar-flare"]
    },
    {
      id: "menu-fire-roasted-oysters",
      slug: "fire-roasted-oysters",
      name: "Coal-Roasted Atlantic Oysters",
      shortName: "Roasted Oysters",
      description: "Half-dozen wild oysters roasted on hearth coals with smoked bone marrow butter, lemon, and sourdough crumbs.",
      serviceIds: ["dinner"],
      sectionId: "dinner-starters",
      category: "starter",
      pricing: { type: "options", baseAmount: 22, currency: "USD", options: [{ label: "Half Dozen", amount: 22 }, { label: "Dozen", amount: 38 }], display: "$22 half / $38 dozen" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["SE"],
      allergenMarkers: ["Shellfish", "Dairy", "Gluten"],
      flavorTags: ["Smoky", "Rich", "Briny", "Fresh"],
      mealStyleTags: ["Starter", "Shared"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "featured-steak",
      imagePath: "images/featured-steak.jpg",
      pairingIds: ["pair-oysters-first-light"]
    },
    {
      id: "menu-hearth-bread",
      slug: "hearth-bread",
      name: "Wood-Fired Hearth Bread & Cultured Butter",
      shortName: "Hearth Bread",
      description: "House sourdough baked over cured oak embers served warm with smoked sea salt and house-churned cultured butter.",
      serviceIds: ["dinner", "brunch"],
      sectionId: "dinner-starters",
      category: "starter",
      pricing: { type: "fixed", baseAmount: 9, currency: "USD", display: "$9" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["V"],
      allergenMarkers: ["Gluten", "Dairy"],
      flavorTags: ["Smoky", "Savory", "Comforting"],
      mealStyleTags: ["Starter", "Shared"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: false,
      imageId: "featured-flatbread",
      imagePath: "images/featured-flatbread.jpg"
    },

    // BRUNCH DISHES
    {
      id: "menu-ember-benedict",
      slug: "ember-benedict",
      name: "Ember Hearth Eggs Benedict",
      shortName: "Ember Benedict",
      description: "Poached farm eggs over wood-grilled pork belly, toasted brioche, and smoky harissa hollandaise.",
      serviceIds: ["brunch"],
      sectionId: "brunch-mains",
      category: "main",
      pricing: { type: "fixed", baseAmount: 19, currency: "USD", display: "$19" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["SP"],
      allergenMarkers: ["Egg", "Gluten", "Dairy", "Pork"],
      flavorTags: ["Smoky", "Rich", "Spiced", "Savory"],
      mealStyleTags: ["Brunch", "Main"],
      shareable: false,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "wood-fired-hearth",
      imagePath: "images/wood-fired-hearth.jpg"
    },
    {
      id: "menu-short-rib-hash",
      slug: "short-rib-hash",
      name: "Smoked Short Rib Skillet Hash",
      shortName: "Short Rib Hash",
      description: "Crispy cast-iron fingerling potatoes, shredded oak-smoked short rib, roasted peppers, and sunny farm egg.",
      serviceIds: ["brunch"],
      sectionId: "brunch-mains",
      category: "main",
      pricing: { type: "fixed", baseAmount: 21, currency: "USD", display: "$21" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["GF"],
      allergenMarkers: ["Egg"],
      flavorTags: ["Smoky", "Savory", "Comforting", "Rich"],
      mealStyleTags: ["Brunch", "Main"],
      shareable: false,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "featured-steak",
      imagePath: "images/featured-steak.jpg"
    },
    {
      id: "menu-peach-french-toast",
      slug: "peach-french-toast",
      name: "Wood-Fired Peach French Toast",
      shortName: "Peach French Toast",
      description: "Thick brioche soaked in vanilla custard, caramelized hearth peaches, bourbon whipped cream, and smoked maple syrup.",
      serviceIds: ["brunch"],
      sectionId: "brunch-mains",
      category: "main",
      pricing: { type: "fixed", baseAmount: 17, currency: "USD", display: "$17" },
      active: true,
      seasonal: true,
      seasonalLabel: "Summer Peach",
      dietaryMarkers: ["V"],
      allergenMarkers: ["Gluten", "Dairy", "Egg"],
      flavorTags: ["Sweet", "Smoky", "Orchard Fruit", "Rich"],
      mealStyleTags: ["Brunch", "Dessert"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "lounge-ambiance",
      imagePath: "images/lounge-ambiance.jpg"
    },

    // COCKTAILS (ALCOHOLIC)
    {
      id: "menu-copper-moon",
      slug: "copper-moon",
      name: "Copper Moon Rye Cocktail",
      shortName: "Copper Moon",
      description: "High-rye bourbon, charred cedar smoked syrup, amaro averna, black walnut bitters, and flamed orange peel.",
      serviceIds: ["drinks", "dinner"],
      sectionId: "drinks-cocktails",
      category: "cocktail",
      pricing: { type: "fixed", baseAmount: 17, currency: "USD", display: "$17" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["CF"],
      allergenMarkers: ["Alcohol", "Tree Nuts"],
      flavorTags: ["Smoky", "Bittersweet", "Rich", "Spiced"],
      mealStyleTags: ["Cocktail"],
      shareable: false,
      alcoholStatus: true,
      zeroProof: false,
      featured: true,
      imageId: "cosmic-cocktail",
      imagePath: "images/cosmic-cocktail.jpg",
      pairingIds: ["pair-short-rib-copper-moon"]
    },
    {
      id: "menu-solar-flare",
      slug: "solar-flare",
      name: "Solar Flare Mezcal Paloma",
      shortName: "Solar Flare",
      description: "Oaxacan mezcal, charred pink grapefruit juice, blood orange liqueur, lime, and volcanic smoked salt rim.",
      serviceIds: ["drinks", "dinner", "brunch"],
      sectionId: "drinks-cocktails",
      category: "cocktail",
      pricing: { type: "fixed", baseAmount: 16, currency: "USD", display: "$16" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["SP"],
      allergenMarkers: ["Alcohol"],
      flavorTags: ["Smoky", "Citrus", "Tart", "Fresh"],
      mealStyleTags: ["Cocktail"],
      shareable: false,
      alcoholStatus: true,
      zeroProof: false,
      featured: true,
      imageId: "cosmic-cocktail",
      imagePath: "images/cosmic-cocktail.jpg"
    },
    {
      id: "menu-first-light-spritz",
      slug: "first-light-spritz",
      name: "First Light Botanical Spritz",
      shortName: "First Light Spritz",
      description: "Artisanal gin, wild elderflower liqueur, charred lemon oleo-saccharum, prosecco, and fresh rosemary sprig.",
      serviceIds: ["drinks", "dinner", "brunch"],
      sectionId: "drinks-cocktails",
      category: "cocktail",
      pricing: { type: "fixed", baseAmount: 15, currency: "USD", display: "$15" },
      active: true,
      seasonal: false,
      dietaryMarkers: [],
      allergenMarkers: ["Alcohol"],
      flavorTags: ["Bright", "Herbal", "Citrus", "Fresh"],
      mealStyleTags: ["Cocktail"],
      shareable: false,
      alcoholStatus: true,
      zeroProof: false,
      featured: true,
      imageId: "cosmic-cocktail",
      imagePath: "images/cosmic-cocktail.jpg"
    },
    {
      id: "menu-espresso-martini",
      slug: "espresso-martini",
      name: "Event Horizon Espresso Martini",
      shortName: "Espresso Martini",
      description: "Small-batch vodka, cold brew espresso reduction, dark cacao liqueur, and charred hazelnut foam.",
      serviceIds: ["drinks", "dessert"],
      sectionId: "drinks-cocktails",
      category: "cocktail",
      pricing: { type: "fixed", baseAmount: 18, currency: "USD", display: "$18" },
      active: true,
      seasonal: false,
      dietaryMarkers: [],
      allergenMarkers: ["Alcohol", "Tree Nuts"],
      flavorTags: ["Coffee", "Rich", "Bittersweet", "Comforting"],
      mealStyleTags: ["Cocktail", "Dessert"],
      shareable: false,
      alcoholStatus: true,
      zeroProof: false,
      featured: true,
      imageId: "cosmic-cocktail",
      imagePath: "images/cosmic-cocktail.jpg"
    },

    // ZERO-PROOF DRINKS
    {
      id: "menu-lunar-bloom",
      slug: "lunar-bloom",
      name: "Lunar Bloom Zero-Proof Elixir",
      shortName: "Lunar Bloom",
      description: "Distilled zero-proof botanical spirit, white peach puree, jasmine tea reduction, fresh lemon, and lavender mist.",
      serviceIds: ["drinks", "dinner", "brunch"],
      sectionId: "drinks-zero-proof",
      category: "zero-proof",
      pricing: { type: "fixed", baseAmount: 12, currency: "USD", display: "$12" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["VG", "GF"],
      allergenMarkers: [],
      flavorTags: ["Floral", "Citrus", "Fresh", "Orchard Fruit"],
      mealStyleTags: ["Zero-Proof"],
      shareable: false,
      alcoholStatus: false,
      zeroProof: true,
      featured: true,
      imageId: "cosmic-cocktail",
      imagePath: "images/cosmic-cocktail.jpg"
    },
    {
      id: "menu-garden-orbit",
      slug: "garden-orbit",
      name: "Garden Orbit Sparkler",
      shortName: "Garden Orbit",
      description: "Pressed cucumber, fresh basil, lime juice, ginger beer, and atomized sea salt blossom.",
      serviceIds: ["drinks", "dinner", "brunch"],
      sectionId: "drinks-zero-proof",
      category: "zero-proof",
      pricing: { type: "fixed", baseAmount: 11, currency: "USD", display: "$11" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["VG", "GF"],
      allergenMarkers: [],
      flavorTags: ["Herbal", "Fresh", "Bright", "Spiced"],
      mealStyleTags: ["Zero-Proof"],
      shareable: false,
      alcoholStatus: false,
      zeroProof: true,
      featured: true,
      imageId: "cosmic-cocktail",
      imagePath: "images/cosmic-cocktail.jpg"
    },
    {
      id: "menu-ember-tonic",
      slug: "ember-tonic",
      name: "Ember Smoked Tea & Tonic",
      shortName: "Ember Tonic",
      description: "Lapsang souchong smoked tea infusion, tonic water, grapefruit twist, and charred rosemary.",
      serviceIds: ["drinks", "dinner"],
      sectionId: "drinks-zero-proof",
      category: "zero-proof",
      pricing: { type: "fixed", baseAmount: 10, currency: "USD", display: "$10" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["VG", "GF"],
      allergenMarkers: [],
      flavorTags: ["Smoky", "Bitter", "Herbal"],
      mealStyleTags: ["Zero-Proof"],
      shareable: false,
      alcoholStatus: false,
      zeroProof: true,
      featured: false,
      imageId: "cosmic-cocktail",
      imagePath: "images/cosmic-cocktail.jpg"
    },

    // DESSERTS
    {
      id: "menu-burnt-honey-cheesecake",
      slug: "burnt-honey-cheesecake",
      name: "Burnt Honey & Hearth Salt Cheesecake",
      shortName: "Burnt Honey Cheesecake",
      description: "Caramelized wildflower honey cheesecake over smoked graham crust with roasted fig jam and flaked Maldon sea salt.",
      serviceIds: ["dessert", "dinner"],
      sectionId: "dessert",
      category: "dessert",
      pricing: { type: "fixed", baseAmount: 14, currency: "USD", display: "$14" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["V"],
      allergenMarkers: ["Dairy", "Gluten", "Egg", "Honey"],
      flavorTags: ["Sweet", "Rich", "Smoky", "Comforting"],
      mealStyleTags: ["Dessert"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "lounge-ambiance",
      imagePath: "images/lounge-ambiance.jpg"
    },
    {
      id: "menu-dark-chocolate-torte",
      slug: "dark-chocolate-torte",
      name: "Oak-Smoked Dark Chocolate Torte",
      shortName: "Dark Chocolate Torte",
      description: "70% Valrhona dark chocolate torte infused with smoked cherrywood, espresso ganache, and hazelnut praline.",
      serviceIds: ["dessert", "dinner"],
      sectionId: "dessert",
      category: "dessert",
      pricing: { type: "fixed", baseAmount: 15, currency: "USD", display: "$15" },
      active: true,
      seasonal: false,
      dietaryMarkers: ["V", "GF"],
      allergenMarkers: ["Dairy", "Egg", "Tree Nuts"],
      flavorTags: ["Bittersweet", "Rich", "Smoky", "Coffee"],
      mealStyleTags: ["Dessert"],
      shareable: true,
      alcoholStatus: false,
      zeroProof: false,
      featured: true,
      imageId: "lounge-ambiance",
      imagePath: "images/lounge-ambiance.jpg"
    }
  ]
};
